name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Generate test coverage
        run: npm run test:coverage

  deploy:
    name: Deploy
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
            --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }} \
            --env AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }} \
            --env MAILCHIMP_API_KEY=${{ secrets.MAILCHIMP_API_KEY }} \
            --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --env JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
            --yes
